FROM jenkins/jenkins:lts-centos
USER root
RUN yum update -y
RUN yum install redhat-rpm-config -y
RUN yum install -y git
#RUN yum groupinstall -y “development tools”
RUN yum install -y wget
RUN yum install -y python3
RUN cp /usr/bin/python3 /usr/bin/python
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN export PATH=~/.local/bin:$PATH
RUN source ~/.bash_profile
RUN yum install gcc  krb5-devel krb5-workstation -y
RUN pip3 install awscli --upgrade --user
#RUN yum install -y unzip && cd /tmp && curl -O https://s3.amazonaws.com/aws-cli/awscli-bundle.zip && unzip awscli-bundle.zip && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
RUN yum install python3-devel -y
RUN export PATH=~/.local/bin:$PATH
RUN source ~/.bash_profile
#RUN cd /tmp &&  curl -O https://s3.amazonaws.com/aws-cli/awscli-bundle.zip && unzip awscli-bundle.zip && ./awscli-bundle/install  -i /usr/local/aws -b /usr/local/bin/aws
#RUN pip install aws-adfs
# Terraform
#RUN cd /tmp
#RUN wget 


# To build image
# docker build -t jenkins-test1 .

#Create local directory to map jenkins data to local
# mkdir /docker/jenkins/home_jenkins

#Run Docker
# docker run -d  --name jekins-docker -p 8080:8080 -p 50000:50000 -v /docker/jenkins/home_jenkins:/var/jenkins_home  jenkins-test1
# docker run -d --name jenkins-svr -p 8080:8080 -p 50000:50000 -v /docker/jenkins:/var/jenkins_home  dockerfile
